### ISSUE TITLE
Cannot read property 'secret' of null

### ISSUE THREAD

**Issue by Filliposniper** [hardillb/2FA-Demo#2]
As you may have noticed your 2faDemo app is down at the moment due to unhandled Error event.

I tried to Login to the G2fa without having to first setup the G2fa Login, and that throws up an error.
I suggest you provide a function that checks to ensure that a user must've setup the G2fa or Fido-2fa before the person can complete the 2fa login process. Also a function that handles an invalid code to avoid Errors

**Comment by hardillb** [comment]
Feel free to submit a pull request
